name: Sslh add-on
version: "1.5.4"
slug: hasslh
description: Sslh add-on
url: "https://github.com/cavaliere78/addons/tree/main/hasslh"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world2..."
schema:
  message: "str?"
image: "cavaliere78/{arch}-addon-hasslh"
