name: Sslh add-on
version: "1.5.7"
slug: hasslh
description: Sslh add-on
url: "https://github.com/cavaliere78/addons/tree/main/hasslh"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  sslh_opts: "-f --user root --listen 0.0.0.0:443 --ssh 192.168.1.120:22 --anyprot 192.168.1.120:4443"
schema:
  message: "str?"
image: "cavaliere78/{arch}-addon-hasslh"
