name: Sslh add-on
version: "1.5.0"
slug: ha_sslh
description: Sslh add-on
url: "https://github.com/home-assistant/addons-ha_sslh/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "cavaliere78/{arch}-addon-ha_sslh"
